//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 

namespace NativeUNLOCO
{
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.cargowise.com/Schemas/Native/2011/11")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.cargowise.com/Schemas/Native/2011/11", IsNullable = false)]
    public partial class Native
    {

        private NativeHeader headerField;

        private NativeBody bodyField;

        private string versionField;

        /// <remarks/>
        public NativeHeader Header
        {
            get
            {
                return this.headerField;
            }
            set
            {
                this.headerField = value;
            }
        }

        /// <remarks/>
        public NativeBody Body
        {
            get
            {
                return this.bodyField;
            }
            set
            {
                this.bodyField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "token")]
        public string version
        {
            get
            {
                return this.versionField;
            }
            set
            {
                this.versionField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.cargowise.com/Schemas/Native/2011/11")]
    public partial class NativeHeader
    {

        private string ownerCodeField;

        private bool enableCodeMappingField;

        private bool enableCodeMappingFieldSpecified;

        private DataContext dataContextField;

        /// <remarks/>
        public string OwnerCode
        {
            get
            {
                return this.ownerCodeField;
            }
            set
            {
                this.ownerCodeField = value;
            }
        }

        /// <remarks/>
        public bool EnableCodeMapping
        {
            get
            {
                return this.enableCodeMappingField;
            }
            set
            {
                this.enableCodeMappingField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool EnableCodeMappingSpecified
        {
            get
            {
                return this.enableCodeMappingFieldSpecified;
            }
            set
            {
                this.enableCodeMappingFieldSpecified = value;
            }
        }

        /// <remarks/>
        public DataContext DataContext
        {
            get
            {
                return this.dataContextField;
            }
            set
            {
                this.dataContextField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.cargowise.com/Schemas/Universal/2011/11")]
    public partial class DataContext
    {

        private DataSource[] dataSourceCollectionField;

        private DataContextAction actionField;

        private bool actionFieldSpecified;

        private CodeDescriptionPair actionPurposeField;

        private bool codesMappedToTargetField;

        private bool codesMappedToTargetFieldSpecified;

        private Company companyField;

        private string dataProviderField;

        private DocumentaryOverride documentaryOverrideField;

        private string enterpriseIDField;

        private Branch eventBranchField;

        private Department eventDepartmentField;

        private string eventReferenceField;

        private CodeDescriptionPair eventTypeField;

        private Staff eventUserField;

        private string serverIDField;

        private int triggerCountField;

        private bool triggerCountFieldSpecified;

        private string triggerDateField;

        private string triggerDescriptionField;

        private string triggerReferenceField;

        private DataContextTriggerType triggerTypeField;

        private bool triggerTypeFieldSpecified;

        private DataTarget[] dataTargetCollectionField;

        private RecipientRole[] recipientRoleCollectionField;

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable = false)]
        public DataSource[] DataSourceCollection
        {
            get
            {
                return this.dataSourceCollectionField;
            }
            set
            {
                this.dataSourceCollectionField = value;
            }
        }

        /// <remarks/>
        public DataContextAction Action
        {
            get
            {
                return this.actionField;
            }
            set
            {
                this.actionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ActionSpecified
        {
            get
            {
                return this.actionFieldSpecified;
            }
            set
            {
                this.actionFieldSpecified = value;
            }
        }

        /// <remarks/>
        public CodeDescriptionPair ActionPurpose
        {
            get
            {
                return this.actionPurposeField;
            }
            set
            {
                this.actionPurposeField = value;
            }
        }

        /// <remarks/>
        public bool CodesMappedToTarget
        {
            get
            {
                return this.codesMappedToTargetField;
            }
            set
            {
                this.codesMappedToTargetField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CodesMappedToTargetSpecified
        {
            get
            {
                return this.codesMappedToTargetFieldSpecified;
            }
            set
            {
                this.codesMappedToTargetFieldSpecified = value;
            }
        }

        /// <remarks/>
        public Company Company
        {
            get
            {
                return this.companyField;
            }
            set
            {
                this.companyField = value;
            }
        }

        /// <remarks/>
        public string DataProvider
        {
            get
            {
                return this.dataProviderField;
            }
            set
            {
                this.dataProviderField = value;
            }
        }

        /// <remarks/>
        public DocumentaryOverride DocumentaryOverride
        {
            get
            {
                return this.documentaryOverrideField;
            }
            set
            {
                this.documentaryOverrideField = value;
            }
        }

        /// <remarks/>
        public string EnterpriseID
        {
            get
            {
                return this.enterpriseIDField;
            }
            set
            {
                this.enterpriseIDField = value;
            }
        }

        /// <remarks/>
        public Branch EventBranch
        {
            get
            {
                return this.eventBranchField;
            }
            set
            {
                this.eventBranchField = value;
            }
        }

        /// <remarks/>
        public Department EventDepartment
        {
            get
            {
                return this.eventDepartmentField;
            }
            set
            {
                this.eventDepartmentField = value;
            }
        }

        /// <remarks/>
        public string EventReference
        {
            get
            {
                return this.eventReferenceField;
            }
            set
            {
                this.eventReferenceField = value;
            }
        }

        /// <remarks/>
        public CodeDescriptionPair EventType
        {
            get
            {
                return this.eventTypeField;
            }
            set
            {
                this.eventTypeField = value;
            }
        }

        /// <remarks/>
        public Staff EventUser
        {
            get
            {
                return this.eventUserField;
            }
            set
            {
                this.eventUserField = value;
            }
        }

        /// <remarks/>
        public string ServerID
        {
            get
            {
                return this.serverIDField;
            }
            set
            {
                this.serverIDField = value;
            }
        }

        /// <remarks/>
        public int TriggerCount
        {
            get
            {
                return this.triggerCountField;
            }
            set
            {
                this.triggerCountField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TriggerCountSpecified
        {
            get
            {
                return this.triggerCountFieldSpecified;
            }
            set
            {
                this.triggerCountFieldSpecified = value;
            }
        }

        /// <remarks/>
        public string TriggerDate
        {
            get
            {
                return this.triggerDateField;
            }
            set
            {
                this.triggerDateField = value;
            }
        }

        /// <remarks/>
        public string TriggerDescription
        {
            get
            {
                return this.triggerDescriptionField;
            }
            set
            {
                this.triggerDescriptionField = value;
            }
        }

        /// <remarks/>
        public string TriggerReference
        {
            get
            {
                return this.triggerReferenceField;
            }
            set
            {
                this.triggerReferenceField = value;
            }
        }

        /// <remarks/>
        public DataContextTriggerType TriggerType
        {
            get
            {
                return this.triggerTypeField;
            }
            set
            {
                this.triggerTypeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TriggerTypeSpecified
        {
            get
            {
                return this.triggerTypeFieldSpecified;
            }
            set
            {
                this.triggerTypeFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable = false)]
        public DataTarget[] DataTargetCollection
        {
            get
            {
                return this.dataTargetCollectionField;
            }
            set
            {
                this.dataTargetCollectionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable = false)]
        public RecipientRole[] RecipientRoleCollection
        {
            get
            {
                return this.recipientRoleCollectionField;
            }
            set
            {
                this.recipientRoleCollectionField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.cargowise.com/Schemas/Universal/2011/11")]
    public partial class DataSource
    {

        private string typeField;

        private string keyField;

        /// <remarks/>
        public string Type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }

        /// <remarks/>
        public string Key
        {
            get
            {
                return this.keyField;
            }
            set
            {
                this.keyField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.cargowise.com/Schemas/Universal/2011/11")]
    public partial class RecipientRole
    {

        private RecipientRoleCode codeField;

        private string descriptionField;

        private RecipientRoleServiceCode serviceCodeField;

        private bool serviceCodeFieldSpecified;

        private string serviceDescriptionField;

        /// <remarks/>
        public RecipientRoleCode Code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
            }
        }

        /// <remarks/>
        public string Description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }

        /// <remarks/>
        public RecipientRoleServiceCode ServiceCode
        {
            get
            {
                return this.serviceCodeField;
            }
            set
            {
                this.serviceCodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ServiceCodeSpecified
        {
            get
            {
                return this.serviceCodeFieldSpecified;
            }
            set
            {
                this.serviceCodeFieldSpecified = value;
            }
        }

        /// <remarks/>
        public string ServiceDescription
        {
            get
            {
                return this.serviceDescriptionField;
            }
            set
            {
                this.serviceDescriptionField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.cargowise.com/Schemas/Universal/2011/11")]
    public enum RecipientRoleCode
    {

        /// <remarks/>
        AAD,

        /// <remarks/>
        ACF,

        /// <remarks/>
        ACR,

        /// <remarks/>
        ACT,

        /// <remarks/>
        ACY,

        /// <remarks/>
        AFR,

        /// <remarks/>
        ARP,

        /// <remarks/>
        ASY,

        /// <remarks/>
        BCO,

        /// <remarks/>
        BKP,

        /// <remarks/>
        BRO,

        /// <remarks/>
        BRI,

        /// <remarks/>
        BRE,

        /// <remarks/>
        BRX,

        /// <remarks/>
        BTP,

        /// <remarks/>
        CAP,

        /// <remarks/>
        CAR,

        /// <remarks/>
        CBA,

        /// <remarks/>
        CCA,

        /// <remarks/>
        CD4,

        /// <remarks/>
        CLI,

        /// <remarks/>
        CNE,

        /// <remarks/>
        CNR,

        /// <remarks/>
        COA,

        /// <remarks/>
        CTA,

        /// <remarks/>
        CTG,

        /// <remarks/>
        CTO,

        /// <remarks/>
        CTP,

        /// <remarks/>
        CYD,

        /// <remarks/>
        DAG,

        /// <remarks/>
        DCA,

        /// <remarks/>
        DCF,

        /// <remarks/>
        DCR,

        /// <remarks/>
        DCT,

        /// <remarks/>
        DCY,

        /// <remarks/>
        DTP,

        /// <remarks/>
        FOR,

        /// <remarks/>
        GRP,

        /// <remarks/>
        HCA,

        /// <remarks/>
        HSA,

        /// <remarks/>
        HVL,

        /// <remarks/>
        ICE,

        /// <remarks/>
        IDB,

        /// <remarks/>
        JWG,

        /// <remarks/>
        LCT,

        /// <remarks/>
        NFP,

        /// <remarks/>
        NGP,

        /// <remarks/>
        NVO,

        /// <remarks/>
        ORP,

        /// <remarks/>
        PAG,

        /// <remarks/>
        PCA,

        /// <remarks/>
        PEM,

        /// <remarks/>
        PER,

        /// <remarks/>
        PIM,

        /// <remarks/>
        PIR,

        /// <remarks/>
        PRC,

        /// <remarks/>
        PUP,

        /// <remarks/>
        RAG,

        /// <remarks/>
        SAG,

        /// <remarks/>
        SGA,

        /// <remarks/>
        SPM,

        /// <remarks/>
        SRP,

        /// <remarks/>
        STF,

        /// <remarks/>
        TPC,

        /// <remarks/>
        DTW,

        /// <remarks/>
        ATW,

        /// <remarks/>
        UAM,

        /// <remarks/>
        WAR,

        /// <remarks/>
        WIN,

        /// <remarks/>
        BWI,

        /// <remarks/>
        BWR,

        /// <remarks/>
        WHS,

        /// <remarks/>
        WNS,

        /// <remarks/>
        YER,

        /// <remarks/>
        YIA,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.cargowise.com/Schemas/Universal/2011/11")]
    public enum RecipientRoleServiceCode
    {

        /// <remarks/>
        AMD,

        /// <remarks/>
        BRQ,

        /// <remarks/>
        CBA,

        /// <remarks/>
        HLD,

        /// <remarks/>
        SIN,

        /// <remarks/>
        TWD,

        /// <remarks/>
        TWR,

        /// <remarks/>
        TWX,

        /// <remarks/>
        VGM,

        /// <remarks/>
        TWP,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.cargowise.com/Schemas/Universal/2011/11")]
    public partial class RegistrationNumber
    {

        private RegistrationNumberType typeField;

        private Country countryOfIssueField;

        private string valueField;

        /// <remarks/>
        public RegistrationNumberType Type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }

        /// <remarks/>
        public Country CountryOfIssue
        {
            get
            {
                return this.countryOfIssueField;
            }
            set
            {
                this.countryOfIssueField = value;
            }
        }

        /// <remarks/>
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.cargowise.com/Schemas/Universal/2011/11")]
    public partial class RegistrationNumberType
    {

        private string codeField;

        private string descriptionField;

        /// <remarks/>
        public string Code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
            }
        }

        /// <remarks/>
        public string Description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.cargowise.com/Schemas/Universal/2011/11")]
    public partial class Country
    {

        private string codeField;

        private string nameField;

        /// <remarks/>
        public string Code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
            }
        }

        /// <remarks/>
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.cargowise.com/Schemas/Universal/2011/11")]
    public partial class Language
    {

        private string codeField;

        private string descriptionField;

        /// <remarks/>
        public string Code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
            }
        }

        /// <remarks/>
        public string Description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.cargowise.com/Schemas/Universal/2011/11")]
    public partial class OrganizationLocalAddress
    {

        private string address1Field;

        private string address2Field;

        private string cityField;

        private string companyNameField;

        private Language languageField;

        private string postcodeField;

        private string stateField;

        /// <remarks/>
        public string Address1
        {
            get
            {
                return this.address1Field;
            }
            set
            {
                this.address1Field = value;
            }
        }

        /// <remarks/>
        public string Address2
        {
            get
            {
                return this.address2Field;
            }
            set
            {
                this.address2Field = value;
            }
        }

        /// <remarks/>
        public string City
        {
            get
            {
                return this.cityField;
            }
            set
            {
                this.cityField = value;
            }
        }

        /// <remarks/>
        public string CompanyName
        {
            get
            {
                return this.companyNameField;
            }
            set
            {
                this.companyNameField = value;
            }
        }

        /// <remarks/>
        public Language Language
        {
            get
            {
                return this.languageField;
            }
            set
            {
                this.languageField = value;
            }
        }

        /// <remarks/>
        public string Postcode
        {
            get
            {
                return this.postcodeField;
            }
            set
            {
                this.postcodeField = value;
            }
        }

        /// <remarks/>
        public string State
        {
            get
            {
                return this.stateField;
            }
            set
            {
                this.stateField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.cargowise.com/Schemas/Universal/2011/11")]
    public partial class OrganizationAddressState
    {

        private string descriptionField;

        private string valueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.cargowise.com/Schemas/Universal/2011/11")]
    public partial class UNLOCO
    {

        private string codeField;

        private string nameField;

        /// <remarks/>
        public string Code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
            }
        }

        /// <remarks/>
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.cargowise.com/Schemas/Universal/2011/11")]
    public partial class OrganizationAddress
    {

        private string addressTypeField;

        private string additionalAddressInformationField;

        private string address1Field;

        private string address2Field;

        private bool addressOverrideField;

        private bool addressOverrideFieldSpecified;

        private string addressShortCodeField;

        private string cityField;

        private string companyNameField;

        private string contactField;

        private Country countryField;

        private string emailField;

        private string faxField;

        private string govRegNumField;

        private RegistrationNumberType govRegNumTypeField;

        private bool isResidentialField;

        private bool isResidentialFieldSpecified;

        private string mobileField;

        private string organizationCodeField;

        private string phoneField;

        private UNLOCO portField;

        private string postcodeField;

        private CodeDescriptionPair screeningStatusField;

        private OrganizationAddressState stateField;

        private bool suppressAddressValidationErrorField;

        private bool suppressAddressValidationErrorFieldSpecified;

        private string universalNettingCodeField;

        private string universalOfficeCodeField;

        private OrganizationLocalAddress[] localAddressCollectionField;

        private RegistrationNumber[] registrationNumberCollectionField;

        /// <remarks/>
        public string AddressType
        {
            get
            {
                return this.addressTypeField;
            }
            set
            {
                this.addressTypeField = value;
            }
        }

        /// <remarks/>
        public string AdditionalAddressInformation
        {
            get
            {
                return this.additionalAddressInformationField;
            }
            set
            {
                this.additionalAddressInformationField = value;
            }
        }

        /// <remarks/>
        public string Address1
        {
            get
            {
                return this.address1Field;
            }
            set
            {
                this.address1Field = value;
            }
        }

        /// <remarks/>
        public string Address2
        {
            get
            {
                return this.address2Field;
            }
            set
            {
                this.address2Field = value;
            }
        }

        /// <remarks/>
        public bool AddressOverride
        {
            get
            {
                return this.addressOverrideField;
            }
            set
            {
                this.addressOverrideField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AddressOverrideSpecified
        {
            get
            {
                return this.addressOverrideFieldSpecified;
            }
            set
            {
                this.addressOverrideFieldSpecified = value;
            }
        }

        /// <remarks/>
        public string AddressShortCode
        {
            get
            {
                return this.addressShortCodeField;
            }
            set
            {
                this.addressShortCodeField = value;
            }
        }

        /// <remarks/>
        public string City
        {
            get
            {
                return this.cityField;
            }
            set
            {
                this.cityField = value;
            }
        }

        /// <remarks/>
        public string CompanyName
        {
            get
            {
                return this.companyNameField;
            }
            set
            {
                this.companyNameField = value;
            }
        }

        /// <remarks/>
        public string Contact
        {
            get
            {
                return this.contactField;
            }
            set
            {
                this.contactField = value;
            }
        }

        /// <remarks/>
        public Country Country
        {
            get
            {
                return this.countryField;
            }
            set
            {
                this.countryField = value;
            }
        }

        /// <remarks/>
        public string Email
        {
            get
            {
                return this.emailField;
            }
            set
            {
                this.emailField = value;
            }
        }

        /// <remarks/>
        public string Fax
        {
            get
            {
                return this.faxField;
            }
            set
            {
                this.faxField = value;
            }
        }

        /// <remarks/>
        public string GovRegNum
        {
            get
            {
                return this.govRegNumField;
            }
            set
            {
                this.govRegNumField = value;
            }
        }

        /// <remarks/>
        public RegistrationNumberType GovRegNumType
        {
            get
            {
                return this.govRegNumTypeField;
            }
            set
            {
                this.govRegNumTypeField = value;
            }
        }

        /// <remarks/>
        public bool IsResidential
        {
            get
            {
                return this.isResidentialField;
            }
            set
            {
                this.isResidentialField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IsResidentialSpecified
        {
            get
            {
                return this.isResidentialFieldSpecified;
            }
            set
            {
                this.isResidentialFieldSpecified = value;
            }
        }

        /// <remarks/>
        public string Mobile
        {
            get
            {
                return this.mobileField;
            }
            set
            {
                this.mobileField = value;
            }
        }

        /// <remarks/>
        public string OrganizationCode
        {
            get
            {
                return this.organizationCodeField;
            }
            set
            {
                this.organizationCodeField = value;
            }
        }

        /// <remarks/>
        public string Phone
        {
            get
            {
                return this.phoneField;
            }
            set
            {
                this.phoneField = value;
            }
        }

        /// <remarks/>
        public UNLOCO Port
        {
            get
            {
                return this.portField;
            }
            set
            {
                this.portField = value;
            }
        }

        /// <remarks/>
        public string Postcode
        {
            get
            {
                return this.postcodeField;
            }
            set
            {
                this.postcodeField = value;
            }
        }

        /// <remarks/>
        public CodeDescriptionPair ScreeningStatus
        {
            get
            {
                return this.screeningStatusField;
            }
            set
            {
                this.screeningStatusField = value;
            }
        }

        /// <remarks/>
        public OrganizationAddressState State
        {
            get
            {
                return this.stateField;
            }
            set
            {
                this.stateField = value;
            }
        }

        /// <remarks/>
        public bool SuppressAddressValidationError
        {
            get
            {
                return this.suppressAddressValidationErrorField;
            }
            set
            {
                this.suppressAddressValidationErrorField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SuppressAddressValidationErrorSpecified
        {
            get
            {
                return this.suppressAddressValidationErrorFieldSpecified;
            }
            set
            {
                this.suppressAddressValidationErrorFieldSpecified = value;
            }
        }

        /// <remarks/>
        public string UniversalNettingCode
        {
            get
            {
                return this.universalNettingCodeField;
            }
            set
            {
                this.universalNettingCodeField = value;
            }
        }

        /// <remarks/>
        public string UniversalOfficeCode
        {
            get
            {
                return this.universalOfficeCodeField;
            }
            set
            {
                this.universalOfficeCodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("LocalAddress", IsNullable = false)]
        public OrganizationLocalAddress[] LocalAddressCollection
        {
            get
            {
                return this.localAddressCollectionField;
            }
            set
            {
                this.localAddressCollectionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable = false)]
        public RegistrationNumber[] RegistrationNumberCollection
        {
            get
            {
                return this.registrationNumberCollectionField;
            }
            set
            {
                this.registrationNumberCollectionField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.cargowise.com/Schemas/Universal/2011/11")]
    public partial class CodeDescriptionPair
    {

        private string codeField;

        private string descriptionField;

        /// <remarks/>
        public string Code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
            }
        }

        /// <remarks/>
        public string Description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.cargowise.com/Schemas/Universal/2011/11")]
    public partial class DataTarget
    {

        private string typeField;

        private string keyField;

        private OrganizationAddress ownerField;

        /// <remarks/>
        public string Type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }

        /// <remarks/>
        public string Key
        {
            get
            {
                return this.keyField;
            }
            set
            {
                this.keyField = value;
            }
        }

        /// <remarks/>
        public OrganizationAddress Owner
        {
            get
            {
                return this.ownerField;
            }
            set
            {
                this.ownerField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.cargowise.com/Schemas/Universal/2011/11")]
    public partial class Staff
    {

        private string codeField;

        private string nameField;

        /// <remarks/>
        public string Code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
            }
        }

        /// <remarks/>
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.cargowise.com/Schemas/Universal/2011/11")]
    public partial class Department
    {

        private string codeField;

        private string nameField;

        /// <remarks/>
        public string Code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
            }
        }

        /// <remarks/>
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.cargowise.com/Schemas/Universal/2011/11")]
    public partial class Branch
    {

        private string codeField;

        private string nameField;

        /// <remarks/>
        public string Code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
            }
        }

        /// <remarks/>
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.cargowise.com/Schemas/Universal/2011/11")]
    public partial class DocumentaryOverride
    {

        private int dataVersionField;

        private bool dataVersionFieldSpecified;

        private string documentNameField;

        private bool isSystemDefinedField;

        private bool isSystemDefinedFieldSpecified;

        private CodeDescriptionPair purposeField;

        private int submissionVersionField;

        private bool submissionVersionFieldSpecified;

        /// <remarks/>
        public int DataVersion
        {
            get
            {
                return this.dataVersionField;
            }
            set
            {
                this.dataVersionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DataVersionSpecified
        {
            get
            {
                return this.dataVersionFieldSpecified;
            }
            set
            {
                this.dataVersionFieldSpecified = value;
            }
        }

        /// <remarks/>
        public string DocumentName
        {
            get
            {
                return this.documentNameField;
            }
            set
            {
                this.documentNameField = value;
            }
        }

        /// <remarks/>
        public bool IsSystemDefined
        {
            get
            {
                return this.isSystemDefinedField;
            }
            set
            {
                this.isSystemDefinedField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IsSystemDefinedSpecified
        {
            get
            {
                return this.isSystemDefinedFieldSpecified;
            }
            set
            {
                this.isSystemDefinedFieldSpecified = value;
            }
        }

        /// <remarks/>
        public CodeDescriptionPair Purpose
        {
            get
            {
                return this.purposeField;
            }
            set
            {
                this.purposeField = value;
            }
        }

        /// <remarks/>
        public int SubmissionVersion
        {
            get
            {
                return this.submissionVersionField;
            }
            set
            {
                this.submissionVersionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SubmissionVersionSpecified
        {
            get
            {
                return this.submissionVersionFieldSpecified;
            }
            set
            {
                this.submissionVersionFieldSpecified = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.cargowise.com/Schemas/Universal/2011/11")]
    public partial class Company
    {

        private string codeField;

        private Country countryField;

        private string nameField;

        /// <remarks/>
        public string Code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
            }
        }

        /// <remarks/>
        public Country Country
        {
            get
            {
                return this.countryField;
            }
            set
            {
                this.countryField = value;
            }
        }

        /// <remarks/>
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.cargowise.com/Schemas/Universal/2011/11")]
    public enum DataContextAction
    {

        /// <remarks/>
        Merge,

        /// <remarks/>
        LinkOnly,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.cargowise.com/Schemas/Universal/2011/11")]
    public enum DataContextTriggerType
    {

        /// <remarks/>
        Trigger,

        /// <remarks/>
        Milestone,

        /// <remarks/>
        Exception,

        /// <remarks/>
        Manual,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.cargowise.com/Schemas/Native/2011/11")]
    public partial class NativeBody
    {

        private System.Xml.XmlElement[] anyField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.cargowise.com/Schemas/Native/2011/11")]
    [System.Xml.Serialization.XmlRootAttribute("UNLOCO", Namespace = "http://www.cargowise.com/Schemas/Native/2011/11", IsNullable = false)]
    public partial class UNLOCOData
    {

        private NativeUNLOCO refUNLOCOField;

        private string versionField;

        /// <remarks/>
        public NativeUNLOCO RefUNLOCO
        {
            get
            {
                return this.refUNLOCOField;
            }
            set
            {
                this.refUNLOCOField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "token")]
        public string version
        {
            get
            {
                return this.versionField;
            }
            set
            {
                this.versionField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.cargowise.com/Schemas/Native/2011/11")]
    public partial class NativeUNLOCO
    {

        private string pkField;

        private string codeField;

        private bool isActiveField;

        private bool isActiveFieldSpecified;

        private bool isSystemField;

        private bool isSystemFieldSpecified;

        private bool isUpdatableField;

        private bool isUpdatableFieldSpecified;

        private string portNameField;

        private string nameWithDiacriticalsField;

        private string iATAField;

        private bool hasAirportField;

        private bool hasAirportFieldSpecified;

        private bool hasSeaportField;

        private bool hasSeaportFieldSpecified;

        private bool hasRailField;

        private bool hasRailFieldSpecified;

        private bool hasRoadField;

        private bool hasRoadFieldSpecified;

        private bool hasPostField;

        private bool hasPostFieldSpecified;

        private bool hasCustomsLodgeField;

        private bool hasCustomsLodgeFieldSpecified;

        private bool hasUnloadField;

        private bool hasUnloadFieldSpecified;

        private bool hasStoreField;

        private bool hasStoreFieldSpecified;

        private bool hasTerminalField;

        private bool hasTerminalFieldSpecified;

        private bool hasDischargeField;

        private bool hasDischargeFieldSpecified;

        private bool hasOutportField;

        private bool hasOutportFieldSpecified;

        private bool hasBorderCrossingField;

        private bool hasBorderCrossingFieldSpecified;

        private string iATARegionCodeField;

        private NativeUNLOCORefTimeZoneSet refTimeZoneSetField;

        private NativeUNLOCOCountryCode countryCodeField;

        private NativeUNLOCORefCountryStates refCountryStatesField;

        private NativeUNLOCORefZonePivot[] refZonePivotCollectionField;

        private Action actionField;

        private bool actionFieldSpecified;

        /// <remarks/>
        public string PK
        {
            get
            {
                return this.pkField;
            }
            set
            {
                this.pkField = value;
            }
        }

        /// <remarks/>
        public string Code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
            }
        }

        /// <remarks/>
        public bool IsActive
        {
            get
            {
                return this.isActiveField;
            }
            set
            {
                this.isActiveField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IsActiveSpecified
        {
            get
            {
                return this.isActiveFieldSpecified;
            }
            set
            {
                this.isActiveFieldSpecified = value;
            }
        }

        /// <remarks/>
        public bool IsSystem
        {
            get
            {
                return this.isSystemField;
            }
            set
            {
                this.isSystemField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IsSystemSpecified
        {
            get
            {
                return this.isSystemFieldSpecified;
            }
            set
            {
                this.isSystemFieldSpecified = value;
            }
        }

        /// <remarks/>
        public bool IsUpdatable
        {
            get
            {
                return this.isUpdatableField;
            }
            set
            {
                this.isUpdatableField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IsUpdatableSpecified
        {
            get
            {
                return this.isUpdatableFieldSpecified;
            }
            set
            {
                this.isUpdatableFieldSpecified = value;
            }
        }

        /// <remarks/>
        public string PortName
        {
            get
            {
                return this.portNameField;
            }
            set
            {
                this.portNameField = value;
            }
        }

        /// <remarks/>
        public string NameWithDiacriticals
        {
            get
            {
                return this.nameWithDiacriticalsField;
            }
            set
            {
                this.nameWithDiacriticalsField = value;
            }
        }

        /// <remarks/>
        public string IATA
        {
            get
            {
                return this.iATAField;
            }
            set
            {
                this.iATAField = value;
            }
        }

        /// <remarks/>
        public bool HasAirport
        {
            get
            {
                return this.hasAirportField;
            }
            set
            {
                this.hasAirportField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool HasAirportSpecified
        {
            get
            {
                return this.hasAirportFieldSpecified;
            }
            set
            {
                this.hasAirportFieldSpecified = value;
            }
        }

        /// <remarks/>
        public bool HasSeaport
        {
            get
            {
                return this.hasSeaportField;
            }
            set
            {
                this.hasSeaportField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool HasSeaportSpecified
        {
            get
            {
                return this.hasSeaportFieldSpecified;
            }
            set
            {
                this.hasSeaportFieldSpecified = value;
            }
        }

        /// <remarks/>
        public bool HasRail
        {
            get
            {
                return this.hasRailField;
            }
            set
            {
                this.hasRailField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool HasRailSpecified
        {
            get
            {
                return this.hasRailFieldSpecified;
            }
            set
            {
                this.hasRailFieldSpecified = value;
            }
        }

        /// <remarks/>
        public bool HasRoad
        {
            get
            {
                return this.hasRoadField;
            }
            set
            {
                this.hasRoadField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool HasRoadSpecified
        {
            get
            {
                return this.hasRoadFieldSpecified;
            }
            set
            {
                this.hasRoadFieldSpecified = value;
            }
        }

        /// <remarks/>
        public bool HasPost
        {
            get
            {
                return this.hasPostField;
            }
            set
            {
                this.hasPostField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool HasPostSpecified
        {
            get
            {
                return this.hasPostFieldSpecified;
            }
            set
            {
                this.hasPostFieldSpecified = value;
            }
        }

        /// <remarks/>
        public bool HasCustomsLodge
        {
            get
            {
                return this.hasCustomsLodgeField;
            }
            set
            {
                this.hasCustomsLodgeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool HasCustomsLodgeSpecified
        {
            get
            {
                return this.hasCustomsLodgeFieldSpecified;
            }
            set
            {
                this.hasCustomsLodgeFieldSpecified = value;
            }
        }

        /// <remarks/>
        public bool HasUnload
        {
            get
            {
                return this.hasUnloadField;
            }
            set
            {
                this.hasUnloadField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool HasUnloadSpecified
        {
            get
            {
                return this.hasUnloadFieldSpecified;
            }
            set
            {
                this.hasUnloadFieldSpecified = value;
            }
        }

        /// <remarks/>
        public bool HasStore
        {
            get
            {
                return this.hasStoreField;
            }
            set
            {
                this.hasStoreField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool HasStoreSpecified
        {
            get
            {
                return this.hasStoreFieldSpecified;
            }
            set
            {
                this.hasStoreFieldSpecified = value;
            }
        }

        /// <remarks/>
        public bool HasTerminal
        {
            get
            {
                return this.hasTerminalField;
            }
            set
            {
                this.hasTerminalField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool HasTerminalSpecified
        {
            get
            {
                return this.hasTerminalFieldSpecified;
            }
            set
            {
                this.hasTerminalFieldSpecified = value;
            }
        }

        /// <remarks/>
        public bool HasDischarge
        {
            get
            {
                return this.hasDischargeField;
            }
            set
            {
                this.hasDischargeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool HasDischargeSpecified
        {
            get
            {
                return this.hasDischargeFieldSpecified;
            }
            set
            {
                this.hasDischargeFieldSpecified = value;
            }
        }

        /// <remarks/>
        public bool HasOutport
        {
            get
            {
                return this.hasOutportField;
            }
            set
            {
                this.hasOutportField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool HasOutportSpecified
        {
            get
            {
                return this.hasOutportFieldSpecified;
            }
            set
            {
                this.hasOutportFieldSpecified = value;
            }
        }

        /// <remarks/>
        public bool HasBorderCrossing
        {
            get
            {
                return this.hasBorderCrossingField;
            }
            set
            {
                this.hasBorderCrossingField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool HasBorderCrossingSpecified
        {
            get
            {
                return this.hasBorderCrossingFieldSpecified;
            }
            set
            {
                this.hasBorderCrossingFieldSpecified = value;
            }
        }

        /// <remarks/>
        public string IATARegionCode
        {
            get
            {
                return this.iATARegionCodeField;
            }
            set
            {
                this.iATARegionCodeField = value;
            }
        }

        /// <remarks/>
        public NativeUNLOCORefTimeZoneSet RefTimeZoneSet
        {
            get
            {
                return this.refTimeZoneSetField;
            }
            set
            {
                this.refTimeZoneSetField = value;
            }
        }

        /// <remarks/>
        public NativeUNLOCOCountryCode CountryCode
        {
            get
            {
                return this.countryCodeField;
            }
            set
            {
                this.countryCodeField = value;
            }
        }

        /// <remarks/>
        public NativeUNLOCORefCountryStates RefCountryStates
        {
            get
            {
                return this.refCountryStatesField;
            }
            set
            {
                this.refCountryStatesField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("RefZonePivot", IsNullable = false)]
        public NativeUNLOCORefZonePivot[] RefZonePivotCollection
        {
            get
            {
                return this.refZonePivotCollectionField;
            }
            set
            {
                this.refZonePivotCollectionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public Action Action
        {
            get
            {
                return this.actionField;
            }
            set
            {
                this.actionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ActionSpecified
        {
            get
            {
                return this.actionFieldSpecified;
            }
            set
            {
                this.actionFieldSpecified = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.cargowise.com/Schemas/Native/2011/11")]
    public partial class NativeUNLOCORefTimeZoneSet
    {

        private string timeZoneSetNameField;

        private string pkField;

        private NativeUNLOCORefTimeZoneSetStandardZone standardZoneField;

        private NativeUNLOCORefTimeZoneSetDaylightSavingZone daylightSavingZoneField;

        private Action actionField;

        private bool actionFieldSpecified;

        /// <remarks/>
        public string TimeZoneSetName
        {
            get
            {
                return this.timeZoneSetNameField;
            }
            set
            {
                this.timeZoneSetNameField = value;
            }
        }

        /// <remarks/>
        public string PK
        {
            get
            {
                return this.pkField;
            }
            set
            {
                this.pkField = value;
            }
        }

        /// <remarks/>
        public NativeUNLOCORefTimeZoneSetStandardZone StandardZone
        {
            get
            {
                return this.standardZoneField;
            }
            set
            {
                this.standardZoneField = value;
            }
        }

        /// <remarks/>
        public NativeUNLOCORefTimeZoneSetDaylightSavingZone DaylightSavingZone
        {
            get
            {
                return this.daylightSavingZoneField;
            }
            set
            {
                this.daylightSavingZoneField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public Action Action
        {
            get
            {
                return this.actionField;
            }
            set
            {
                this.actionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ActionSpecified
        {
            get
            {
                return this.actionFieldSpecified;
            }
            set
            {
                this.actionFieldSpecified = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.cargowise.com/Schemas/Native/2011/11")]
    public partial class NativeUNLOCORefTimeZoneSetStandardZone
    {

        private string pkField;

        private Action actionField;

        private bool actionFieldSpecified;

        private string tableNameField;

        /// <remarks/>
        public string PK
        {
            get
            {
                return this.pkField;
            }
            set
            {
                this.pkField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public Action Action
        {
            get
            {
                return this.actionField;
            }
            set
            {
                this.actionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ActionSpecified
        {
            get
            {
                return this.actionFieldSpecified;
            }
            set
            {
                this.actionFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string TableName
        {
            get
            {
                return this.tableNameField;
            }
            set
            {
                this.tableNameField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.cargowise.com/Schemas/Native/2011/11")]
    public enum Action
    {

        /// <remarks/>
        INSERT,

        /// <remarks/>
        UPDATE,

        /// <remarks/>
        MERGE,

        /// <remarks/>
        DELETE,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.cargowise.com/Schemas/Native/2011/11")]
    public partial class NativeUNLOCORefTimeZoneSetDaylightSavingZone
    {

        private string pkField;

        private Action actionField;

        private bool actionFieldSpecified;

        private string tableNameField;

        /// <remarks/>
        public string PK
        {
            get
            {
                return this.pkField;
            }
            set
            {
                this.pkField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public Action Action
        {
            get
            {
                return this.actionField;
            }
            set
            {
                this.actionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ActionSpecified
        {
            get
            {
                return this.actionFieldSpecified;
            }
            set
            {
                this.actionFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string TableName
        {
            get
            {
                return this.tableNameField;
            }
            set
            {
                this.tableNameField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.cargowise.com/Schemas/Native/2011/11")]
    public partial class NativeUNLOCOCountryCode
    {

        private string codeField;

        private string pkField;

        private Action actionField;

        private bool actionFieldSpecified;

        private string tableNameField;

        /// <remarks/>
        public string Code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
            }
        }

        /// <remarks/>
        public string PK
        {
            get
            {
                return this.pkField;
            }
            set
            {
                this.pkField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public Action Action
        {
            get
            {
                return this.actionField;
            }
            set
            {
                this.actionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ActionSpecified
        {
            get
            {
                return this.actionFieldSpecified;
            }
            set
            {
                this.actionFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string TableName
        {
            get
            {
                return this.tableNameField;
            }
            set
            {
                this.tableNameField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.cargowise.com/Schemas/Native/2011/11")]
    public partial class NativeUNLOCORefCountryStates
    {

        private string countryCodeField;

        private string codeField;

        private string pkField;

        private NativeUNLOCORefCountryStatesCountryCodeExternal countryCodeExternalField;

        private Action actionField;

        private bool actionFieldSpecified;

        /// <remarks/>
        public string CountryCode
        {
            get
            {
                return this.countryCodeField;
            }
            set
            {
                this.countryCodeField = value;
            }
        }

        /// <remarks/>
        public string Code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
            }
        }

        /// <remarks/>
        public string PK
        {
            get
            {
                return this.pkField;
            }
            set
            {
                this.pkField = value;
            }
        }

        /// <remarks/>
        public NativeUNLOCORefCountryStatesCountryCodeExternal CountryCodeExternal
        {
            get
            {
                return this.countryCodeExternalField;
            }
            set
            {
                this.countryCodeExternalField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public Action Action
        {
            get
            {
                return this.actionField;
            }
            set
            {
                this.actionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ActionSpecified
        {
            get
            {
                return this.actionFieldSpecified;
            }
            set
            {
                this.actionFieldSpecified = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.cargowise.com/Schemas/Native/2011/11")]
    public partial class NativeUNLOCORefCountryStatesCountryCodeExternal
    {

        private string codeField;

        private string pkField;

        private Action actionField;

        private bool actionFieldSpecified;

        private string tableNameField;

        /// <remarks/>
        public string Code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
            }
        }

        /// <remarks/>
        public string PK
        {
            get
            {
                return this.pkField;
            }
            set
            {
                this.pkField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public Action Action
        {
            get
            {
                return this.actionField;
            }
            set
            {
                this.actionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ActionSpecified
        {
            get
            {
                return this.actionFieldSpecified;
            }
            set
            {
                this.actionFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string TableName
        {
            get
            {
                return this.tableNameField;
            }
            set
            {
                this.tableNameField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.cargowise.com/Schemas/Native/2011/11")]
    public partial class NativeUNLOCORefZonePivot
    {

        private string pkField;

        private NativeUNLOCORefZonePivotRefZoneHeader refZoneHeaderField;

        private Action actionField;

        private bool actionFieldSpecified;

        /// <remarks/>
        public string PK
        {
            get
            {
                return this.pkField;
            }
            set
            {
                this.pkField = value;
            }
        }

        /// <remarks/>
        public NativeUNLOCORefZonePivotRefZoneHeader RefZoneHeader
        {
            get
            {
                return this.refZoneHeaderField;
            }
            set
            {
                this.refZoneHeaderField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public Action Action
        {
            get
            {
                return this.actionField;
            }
            set
            {
                this.actionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ActionSpecified
        {
            get
            {
                return this.actionFieldSpecified;
            }
            set
            {
                this.actionFieldSpecified = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.cargowise.com/Schemas/Native/2011/11")]
    public partial class NativeUNLOCORefZonePivotRefZoneHeader
    {

        private string codeField;

        private string zoneTypeField;

        private string descriptionField;

        private string pkField;

        private Action actionField;

        private bool actionFieldSpecified;

        /// <remarks/>
        public string Code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
            }
        }

        /// <remarks/>
        public string ZoneType
        {
            get
            {
                return this.zoneTypeField;
            }
            set
            {
                this.zoneTypeField = value;
            }
        }

        /// <remarks/>
        public string Description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }

        /// <remarks/>
        public string PK
        {
            get
            {
                return this.pkField;
            }
            set
            {
                this.pkField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public Action Action
        {
            get
            {
                return this.actionField;
            }
            set
            {
                this.actionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ActionSpecified
        {
            get
            {
                return this.actionFieldSpecified;
            }
            set
            {
                this.actionFieldSpecified = value;
            }
        }
    }
}