//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 


/// <remarks/>
namespace NativeRequest
{
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.cargowise.com/Schemas/Native")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.cargowise.com/Schemas/Native", IsNullable = false)]
    public partial class Native
    {

        private NativeBody bodyField;

        /// <remarks/>
        public NativeBody Body
        {
            get
            {
                return this.bodyField;
            }
            set
            {
                this.bodyField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.cargowise.com/Schemas/Native")]
    public partial class NativeBody
    {

        private CriteriaData itemField;

        private ItemChoiceType itemElementNameField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("AcceptabilityBand", typeof(CriteriaData))]
        [System.Xml.Serialization.XmlElementAttribute("Airline", typeof(CriteriaData))]
        [System.Xml.Serialization.XmlElementAttribute("BMSystem", typeof(CriteriaData))]
        [System.Xml.Serialization.XmlElementAttribute("CommodityCode", typeof(CriteriaData))]
        [System.Xml.Serialization.XmlElementAttribute("Company", typeof(CriteriaData))]
        [System.Xml.Serialization.XmlElementAttribute("Container", typeof(CriteriaData))]
        [System.Xml.Serialization.XmlElementAttribute("Country", typeof(CriteriaData))]
        [System.Xml.Serialization.XmlElementAttribute("CurrencyExchangeRate", typeof(CriteriaData))]
        [System.Xml.Serialization.XmlElementAttribute("CusStatement", typeof(CriteriaData))]
        [System.Xml.Serialization.XmlElementAttribute("DangerousGood", typeof(CriteriaData))]
        [System.Xml.Serialization.XmlElementAttribute("Organization", typeof(CriteriaData))]
        [System.Xml.Serialization.XmlElementAttribute("Product", typeof(CriteriaData))]
        [System.Xml.Serialization.XmlElementAttribute("Rate", typeof(CriteriaData))]
        [System.Xml.Serialization.XmlElementAttribute("ServiceLevel", typeof(CriteriaData))]
        [System.Xml.Serialization.XmlElementAttribute("Staff", typeof(CriteriaData))]
        [System.Xml.Serialization.XmlElementAttribute("Tag", typeof(CriteriaData))]
        [System.Xml.Serialization.XmlElementAttribute("TagRule", typeof(CriteriaData))]
        [System.Xml.Serialization.XmlElementAttribute("UNLOCO", typeof(CriteriaData))]
        [System.Xml.Serialization.XmlElementAttribute("Vessel", typeof(CriteriaData))]
        [System.Xml.Serialization.XmlElementAttribute("WorkflowTemplate", typeof(CriteriaData))]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
        public CriteriaData Item
        {
            get
            {
                return this.itemField;
            }
            set
            {
                this.itemField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemChoiceType ItemElementName
        {
            get
            {
                return this.itemElementNameField;
            }
            set
            {
                this.itemElementNameField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.cargowise.com/Schemas/Native")]
    public partial class CriteriaData
    {

        private CriteriaGroupType criteriaGroupField;

        /// <remarks/>
        public CriteriaGroupType CriteriaGroup
        {
            get
            {
                return this.criteriaGroupField;
            }
            set
            {
                this.criteriaGroupField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.cargowise.com/Schemas/Native")]
    public partial class CriteriaGroupType
    {

        private CriteriaType[] criteriaField;

        private TypeEnum typeField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Criteria")]
        public CriteriaType[] Criteria
        {
            get
            {
                return this.criteriaField;
            }
            set
            {
                this.criteriaField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public TypeEnum Type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.cargowise.com/Schemas/Native")]
    public partial class CriteriaType
    {

        private string entityField;

        private string fieldNameField;

        private string valueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Entity
        {
            get
            {
                return this.entityField;
            }
            set
            {
                this.entityField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string FieldName
        {
            get
            {
                return this.fieldNameField;
            }
            set
            {
                this.fieldNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.cargowise.com/Schemas/Native")]
    public enum TypeEnum
    {

        /// <remarks/>
        Key,

        /// <remarks/>
        Partial,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.cargowise.com/Schemas/Native", IncludeInSchema = false)]
    public enum ItemChoiceType
    {

        /// <remarks/>
        AcceptabilityBand,

        /// <remarks/>
        Airline,

        /// <remarks/>
        BMSystem,

        /// <remarks/>
        CommodityCode,

        /// <remarks/>
        Company,

        /// <remarks/>
        Container,

        /// <remarks/>
        Country,

        /// <remarks/>
        CurrencyExchangeRate,

        /// <remarks/>
        CusStatement,

        /// <remarks/>
        DangerousGood,

        /// <remarks/>
        Organization,

        /// <remarks/>
        Product,

        /// <remarks/>
        Rate,

        /// <remarks/>
        ServiceLevel,

        /// <remarks/>
        Staff,

        /// <remarks/>
        Tag,

        /// <remarks/>
        TagRule,

        /// <remarks/>
        UNLOCO,

        /// <remarks/>
        Vessel,

        /// <remarks/>
        WorkflowTemplate,
    }
}