//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 

namespace ShipmentRequest
{
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.cargowise.com/Schemas/Universal/2011/11")]
    [System.Xml.Serialization.XmlRootAttribute("UniversalShipmentRequest", Namespace = "http://www.cargowise.com/Schemas/Universal/2011/11", IsNullable = false)]
    public partial class UniversalShipmentRequestData
    {

        private ShipmentRequest shipmentRequestField;

        private string versionField;

        /// <remarks/>
        public ShipmentRequest ShipmentRequest
        {
            get
            {
                return this.shipmentRequestField;
            }
            set
            {
                this.shipmentRequestField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "token")]
        public string version
        {
            get
            {
                return this.versionField;
            }
            set
            {
                this.versionField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.cargowise.com/Schemas/Universal/2011/11")]
    public partial class ShipmentRequest
    {

        private DataContext dataContextField;

        /// <remarks/>
        public DataContext DataContext
        {
            get
            {
                return this.dataContextField;
            }
            set
            {
                this.dataContextField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.cargowise.com/Schemas/Universal/2011/11")]
    public partial class DataContext
    {

        private DataSource[] dataSourceCollectionField;

        private DataContextAction actionField;

        private bool actionFieldSpecified;

        private CodeDescriptionPair actionPurposeField;

        private bool codesMappedToTargetField;

        private bool codesMappedToTargetFieldSpecified;

        private Company companyField;

        private string dataProviderField;

        private DocumentaryOverride documentaryOverrideField;

        private string enterpriseIDField;

        private Branch eventBranchField;

        private Department eventDepartmentField;

        private string eventReferenceField;

        private CodeDescriptionPair eventTypeField;

        private Staff eventUserField;

        private string serverIDField;

        private int triggerCountField;

        private bool triggerCountFieldSpecified;

        private string triggerDateField;

        private string triggerDescriptionField;

        private string triggerReferenceField;

        private DataContextTriggerType triggerTypeField;

        private bool triggerTypeFieldSpecified;

        private DataTarget[] dataTargetCollectionField;

        private RecipientRole[] recipientRoleCollectionField;

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable = false)]
        public DataSource[] DataSourceCollection
        {
            get
            {
                return this.dataSourceCollectionField;
            }
            set
            {
                this.dataSourceCollectionField = value;
            }
        }

        /// <remarks/>
        public DataContextAction Action
        {
            get
            {
                return this.actionField;
            }
            set
            {
                this.actionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ActionSpecified
        {
            get
            {
                return this.actionFieldSpecified;
            }
            set
            {
                this.actionFieldSpecified = value;
            }
        }

        /// <remarks/>
        public CodeDescriptionPair ActionPurpose
        {
            get
            {
                return this.actionPurposeField;
            }
            set
            {
                this.actionPurposeField = value;
            }
        }

        /// <remarks/>
        public bool CodesMappedToTarget
        {
            get
            {
                return this.codesMappedToTargetField;
            }
            set
            {
                this.codesMappedToTargetField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CodesMappedToTargetSpecified
        {
            get
            {
                return this.codesMappedToTargetFieldSpecified;
            }
            set
            {
                this.codesMappedToTargetFieldSpecified = value;
            }
        }

        /// <remarks/>
        public Company Company
        {
            get
            {
                return this.companyField;
            }
            set
            {
                this.companyField = value;
            }
        }

        /// <remarks/>
        public string DataProvider
        {
            get
            {
                return this.dataProviderField;
            }
            set
            {
                this.dataProviderField = value;
            }
        }

        /// <remarks/>
        public DocumentaryOverride DocumentaryOverride
        {
            get
            {
                return this.documentaryOverrideField;
            }
            set
            {
                this.documentaryOverrideField = value;
            }
        }

        /// <remarks/>
        public string EnterpriseID
        {
            get
            {
                return this.enterpriseIDField;
            }
            set
            {
                this.enterpriseIDField = value;
            }
        }

        /// <remarks/>
        public Branch EventBranch
        {
            get
            {
                return this.eventBranchField;
            }
            set
            {
                this.eventBranchField = value;
            }
        }

        /// <remarks/>
        public Department EventDepartment
        {
            get
            {
                return this.eventDepartmentField;
            }
            set
            {
                this.eventDepartmentField = value;
            }
        }

        /// <remarks/>
        public string EventReference
        {
            get
            {
                return this.eventReferenceField;
            }
            set
            {
                this.eventReferenceField = value;
            }
        }

        /// <remarks/>
        public CodeDescriptionPair EventType
        {
            get
            {
                return this.eventTypeField;
            }
            set
            {
                this.eventTypeField = value;
            }
        }

        /// <remarks/>
        public Staff EventUser
        {
            get
            {
                return this.eventUserField;
            }
            set
            {
                this.eventUserField = value;
            }
        }

        /// <remarks/>
        public string ServerID
        {
            get
            {
                return this.serverIDField;
            }
            set
            {
                this.serverIDField = value;
            }
        }

        /// <remarks/>
        public int TriggerCount
        {
            get
            {
                return this.triggerCountField;
            }
            set
            {
                this.triggerCountField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TriggerCountSpecified
        {
            get
            {
                return this.triggerCountFieldSpecified;
            }
            set
            {
                this.triggerCountFieldSpecified = value;
            }
        }

        /// <remarks/>
        public string TriggerDate
        {
            get
            {
                return this.triggerDateField;
            }
            set
            {
                this.triggerDateField = value;
            }
        }

        /// <remarks/>
        public string TriggerDescription
        {
            get
            {
                return this.triggerDescriptionField;
            }
            set
            {
                this.triggerDescriptionField = value;
            }
        }

        /// <remarks/>
        public string TriggerReference
        {
            get
            {
                return this.triggerReferenceField;
            }
            set
            {
                this.triggerReferenceField = value;
            }
        }

        /// <remarks/>
        public DataContextTriggerType TriggerType
        {
            get
            {
                return this.triggerTypeField;
            }
            set
            {
                this.triggerTypeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TriggerTypeSpecified
        {
            get
            {
                return this.triggerTypeFieldSpecified;
            }
            set
            {
                this.triggerTypeFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable = false)]
        public DataTarget[] DataTargetCollection
        {
            get
            {
                return this.dataTargetCollectionField;
            }
            set
            {
                this.dataTargetCollectionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable = false)]
        public RecipientRole[] RecipientRoleCollection
        {
            get
            {
                return this.recipientRoleCollectionField;
            }
            set
            {
                this.recipientRoleCollectionField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.cargowise.com/Schemas/Universal/2011/11")]
    public partial class DataSource
    {

        private string typeField;

        private string keyField;

        /// <remarks/>
        public string Type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }

        /// <remarks/>
        public string Key
        {
            get
            {
                return this.keyField;
            }
            set
            {
                this.keyField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.cargowise.com/Schemas/Universal/2011/11")]
    public partial class RecipientRole
    {

        private RecipientRoleCode codeField;

        private string descriptionField;

        private RecipientRoleServiceCode serviceCodeField;

        private bool serviceCodeFieldSpecified;

        private string serviceDescriptionField;

        /// <remarks/>
        public RecipientRoleCode Code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
            }
        }

        /// <remarks/>
        public string Description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }

        /// <remarks/>
        public RecipientRoleServiceCode ServiceCode
        {
            get
            {
                return this.serviceCodeField;
            }
            set
            {
                this.serviceCodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ServiceCodeSpecified
        {
            get
            {
                return this.serviceCodeFieldSpecified;
            }
            set
            {
                this.serviceCodeFieldSpecified = value;
            }
        }

        /// <remarks/>
        public string ServiceDescription
        {
            get
            {
                return this.serviceDescriptionField;
            }
            set
            {
                this.serviceDescriptionField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.cargowise.com/Schemas/Universal/2011/11")]
    public enum RecipientRoleCode
    {

        /// <remarks/>
        AAD,

        /// <remarks/>
        ACF,

        /// <remarks/>
        ACR,

        /// <remarks/>
        ACT,

        /// <remarks/>
        ACY,

        /// <remarks/>
        AFR,

        /// <remarks/>
        ARP,

        /// <remarks/>
        ASY,

        /// <remarks/>
        BCO,

        /// <remarks/>
        BKP,

        /// <remarks/>
        BRO,

        /// <remarks/>
        BRI,

        /// <remarks/>
        BRE,

        /// <remarks/>
        BRX,

        /// <remarks/>
        BTP,

        /// <remarks/>
        CAP,

        /// <remarks/>
        CAR,

        /// <remarks/>
        CBA,

        /// <remarks/>
        CCA,

        /// <remarks/>
        CD4,

        /// <remarks/>
        CLI,

        /// <remarks/>
        CNE,

        /// <remarks/>
        CNR,

        /// <remarks/>
        COA,

        /// <remarks/>
        CTA,

        /// <remarks/>
        CTG,

        /// <remarks/>
        CTO,

        /// <remarks/>
        CTP,

        /// <remarks/>
        CYD,

        /// <remarks/>
        DAG,

        /// <remarks/>
        DCA,

        /// <remarks/>
        DCF,

        /// <remarks/>
        DCR,

        /// <remarks/>
        DCT,

        /// <remarks/>
        DCY,

        /// <remarks/>
        DTP,

        /// <remarks/>
        FOR,

        /// <remarks/>
        GRP,

        /// <remarks/>
        HCA,

        /// <remarks/>
        HSA,

        /// <remarks/>
        HVL,

        /// <remarks/>
        ICE,

        /// <remarks/>
        IDB,

        /// <remarks/>
        JWG,

        /// <remarks/>
        LCT,

        /// <remarks/>
        NFP,

        /// <remarks/>
        NGP,

        /// <remarks/>
        NVO,

        /// <remarks/>
        ORP,

        /// <remarks/>
        PAG,

        /// <remarks/>
        PCA,

        /// <remarks/>
        PEM,

        /// <remarks/>
        PER,

        /// <remarks/>
        PIM,

        /// <remarks/>
        PIR,

        /// <remarks/>
        PRC,

        /// <remarks/>
        PUP,

        /// <remarks/>
        RAG,

        /// <remarks/>
        SAG,

        /// <remarks/>
        SGA,

        /// <remarks/>
        SPM,

        /// <remarks/>
        SRP,

        /// <remarks/>
        STF,

        /// <remarks/>
        TPC,

        /// <remarks/>
        DTW,

        /// <remarks/>
        ATW,

        /// <remarks/>
        UAM,

        /// <remarks/>
        WAR,

        /// <remarks/>
        WIN,

        /// <remarks/>
        BWI,

        /// <remarks/>
        BWR,

        /// <remarks/>
        WHS,

        /// <remarks/>
        WNS,

        /// <remarks/>
        YER,

        /// <remarks/>
        YIA,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.cargowise.com/Schemas/Universal/2011/11")]
    public enum RecipientRoleServiceCode
    {

        /// <remarks/>
        AMD,

        /// <remarks/>
        BRQ,

        /// <remarks/>
        CBA,

        /// <remarks/>
        HLD,

        /// <remarks/>
        SIN,

        /// <remarks/>
        TWD,

        /// <remarks/>
        TWR,

        /// <remarks/>
        TWX,

        /// <remarks/>
        VGM,

        /// <remarks/>
        TWP,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.cargowise.com/Schemas/Universal/2011/11")]
    public partial class RegistrationNumber
    {

        private RegistrationNumberType typeField;

        private Country countryOfIssueField;

        private string valueField;

        /// <remarks/>
        public RegistrationNumberType Type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }

        /// <remarks/>
        public Country CountryOfIssue
        {
            get
            {
                return this.countryOfIssueField;
            }
            set
            {
                this.countryOfIssueField = value;
            }
        }

        /// <remarks/>
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.cargowise.com/Schemas/Universal/2011/11")]
    public partial class RegistrationNumberType
    {

        private string codeField;

        private string descriptionField;

        /// <remarks/>
        public string Code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
            }
        }

        /// <remarks/>
        public string Description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.cargowise.com/Schemas/Universal/2011/11")]
    public partial class Country
    {

        private string codeField;

        private string nameField;

        /// <remarks/>
        public string Code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
            }
        }

        /// <remarks/>
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.cargowise.com/Schemas/Universal/2011/11")]
    public partial class Language
    {

        private string codeField;

        private string descriptionField;

        /// <remarks/>
        public string Code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
            }
        }

        /// <remarks/>
        public string Description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.cargowise.com/Schemas/Universal/2011/11")]
    public partial class OrganizationLocalAddress
    {

        private string address1Field;

        private string address2Field;

        private string cityField;

        private string companyNameField;

        private Language languageField;

        private string postcodeField;

        private string stateField;

        /// <remarks/>
        public string Address1
        {
            get
            {
                return this.address1Field;
            }
            set
            {
                this.address1Field = value;
            }
        }

        /// <remarks/>
        public string Address2
        {
            get
            {
                return this.address2Field;
            }
            set
            {
                this.address2Field = value;
            }
        }

        /// <remarks/>
        public string City
        {
            get
            {
                return this.cityField;
            }
            set
            {
                this.cityField = value;
            }
        }

        /// <remarks/>
        public string CompanyName
        {
            get
            {
                return this.companyNameField;
            }
            set
            {
                this.companyNameField = value;
            }
        }

        /// <remarks/>
        public Language Language
        {
            get
            {
                return this.languageField;
            }
            set
            {
                this.languageField = value;
            }
        }

        /// <remarks/>
        public string Postcode
        {
            get
            {
                return this.postcodeField;
            }
            set
            {
                this.postcodeField = value;
            }
        }

        /// <remarks/>
        public string State
        {
            get
            {
                return this.stateField;
            }
            set
            {
                this.stateField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.cargowise.com/Schemas/Universal/2011/11")]
    public partial class OrganizationAddressState
    {

        private string descriptionField;

        private string valueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.cargowise.com/Schemas/Universal/2011/11")]
    public partial class UNLOCO
    {

        private string codeField;

        private string nameField;

        /// <remarks/>
        public string Code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
            }
        }

        /// <remarks/>
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.cargowise.com/Schemas/Universal/2011/11")]
    public partial class OrganizationAddress
    {

        private string addressTypeField;

        private string additionalAddressInformationField;

        private string address1Field;

        private string address2Field;

        private bool addressOverrideField;

        private bool addressOverrideFieldSpecified;

        private string addressShortCodeField;

        private string cityField;

        private string companyNameField;

        private string contactField;

        private Country countryField;

        private string emailField;

        private string faxField;

        private string govRegNumField;

        private RegistrationNumberType govRegNumTypeField;

        private bool isResidentialField;

        private bool isResidentialFieldSpecified;

        private string mobileField;

        private string organizationCodeField;

        private string phoneField;

        private UNLOCO portField;

        private string postcodeField;

        private CodeDescriptionPair screeningStatusField;

        private OrganizationAddressState stateField;

        private bool suppressAddressValidationErrorField;

        private bool suppressAddressValidationErrorFieldSpecified;

        private string universalNettingCodeField;

        private string universalOfficeCodeField;

        private OrganizationLocalAddress[] localAddressCollectionField;

        private RegistrationNumber[] registrationNumberCollectionField;

        /// <remarks/>
        public string AddressType
        {
            get
            {
                return this.addressTypeField;
            }
            set
            {
                this.addressTypeField = value;
            }
        }

        /// <remarks/>
        public string AdditionalAddressInformation
        {
            get
            {
                return this.additionalAddressInformationField;
            }
            set
            {
                this.additionalAddressInformationField = value;
            }
        }

        /// <remarks/>
        public string Address1
        {
            get
            {
                return this.address1Field;
            }
            set
            {
                this.address1Field = value;
            }
        }

        /// <remarks/>
        public string Address2
        {
            get
            {
                return this.address2Field;
            }
            set
            {
                this.address2Field = value;
            }
        }

        /// <remarks/>
        public bool AddressOverride
        {
            get
            {
                return this.addressOverrideField;
            }
            set
            {
                this.addressOverrideField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AddressOverrideSpecified
        {
            get
            {
                return this.addressOverrideFieldSpecified;
            }
            set
            {
                this.addressOverrideFieldSpecified = value;
            }
        }

        /// <remarks/>
        public string AddressShortCode
        {
            get
            {
                return this.addressShortCodeField;
            }
            set
            {
                this.addressShortCodeField = value;
            }
        }

        /// <remarks/>
        public string City
        {
            get
            {
                return this.cityField;
            }
            set
            {
                this.cityField = value;
            }
        }

        /// <remarks/>
        public string CompanyName
        {
            get
            {
                return this.companyNameField;
            }
            set
            {
                this.companyNameField = value;
            }
        }

        /// <remarks/>
        public string Contact
        {
            get
            {
                return this.contactField;
            }
            set
            {
                this.contactField = value;
            }
        }

        /// <remarks/>
        public Country Country
        {
            get
            {
                return this.countryField;
            }
            set
            {
                this.countryField = value;
            }
        }

        /// <remarks/>
        public string Email
        {
            get
            {
                return this.emailField;
            }
            set
            {
                this.emailField = value;
            }
        }

        /// <remarks/>
        public string Fax
        {
            get
            {
                return this.faxField;
            }
            set
            {
                this.faxField = value;
            }
        }

        /// <remarks/>
        public string GovRegNum
        {
            get
            {
                return this.govRegNumField;
            }
            set
            {
                this.govRegNumField = value;
            }
        }

        /// <remarks/>
        public RegistrationNumberType GovRegNumType
        {
            get
            {
                return this.govRegNumTypeField;
            }
            set
            {
                this.govRegNumTypeField = value;
            }
        }

        /// <remarks/>
        public bool IsResidential
        {
            get
            {
                return this.isResidentialField;
            }
            set
            {
                this.isResidentialField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IsResidentialSpecified
        {
            get
            {
                return this.isResidentialFieldSpecified;
            }
            set
            {
                this.isResidentialFieldSpecified = value;
            }
        }

        /// <remarks/>
        public string Mobile
        {
            get
            {
                return this.mobileField;
            }
            set
            {
                this.mobileField = value;
            }
        }

        /// <remarks/>
        public string OrganizationCode
        {
            get
            {
                return this.organizationCodeField;
            }
            set
            {
                this.organizationCodeField = value;
            }
        }

        /// <remarks/>
        public string Phone
        {
            get
            {
                return this.phoneField;
            }
            set
            {
                this.phoneField = value;
            }
        }

        /// <remarks/>
        public UNLOCO Port
        {
            get
            {
                return this.portField;
            }
            set
            {
                this.portField = value;
            }
        }

        /// <remarks/>
        public string Postcode
        {
            get
            {
                return this.postcodeField;
            }
            set
            {
                this.postcodeField = value;
            }
        }

        /// <remarks/>
        public CodeDescriptionPair ScreeningStatus
        {
            get
            {
                return this.screeningStatusField;
            }
            set
            {
                this.screeningStatusField = value;
            }
        }

        /// <remarks/>
        public OrganizationAddressState State
        {
            get
            {
                return this.stateField;
            }
            set
            {
                this.stateField = value;
            }
        }

        /// <remarks/>
        public bool SuppressAddressValidationError
        {
            get
            {
                return this.suppressAddressValidationErrorField;
            }
            set
            {
                this.suppressAddressValidationErrorField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SuppressAddressValidationErrorSpecified
        {
            get
            {
                return this.suppressAddressValidationErrorFieldSpecified;
            }
            set
            {
                this.suppressAddressValidationErrorFieldSpecified = value;
            }
        }

        /// <remarks/>
        public string UniversalNettingCode
        {
            get
            {
                return this.universalNettingCodeField;
            }
            set
            {
                this.universalNettingCodeField = value;
            }
        }

        /// <remarks/>
        public string UniversalOfficeCode
        {
            get
            {
                return this.universalOfficeCodeField;
            }
            set
            {
                this.universalOfficeCodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("LocalAddress", IsNullable = false)]
        public OrganizationLocalAddress[] LocalAddressCollection
        {
            get
            {
                return this.localAddressCollectionField;
            }
            set
            {
                this.localAddressCollectionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable = false)]
        public RegistrationNumber[] RegistrationNumberCollection
        {
            get
            {
                return this.registrationNumberCollectionField;
            }
            set
            {
                this.registrationNumberCollectionField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.cargowise.com/Schemas/Universal/2011/11")]
    public partial class CodeDescriptionPair
    {

        private string codeField;

        private string descriptionField;

        /// <remarks/>
        public string Code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
            }
        }

        /// <remarks/>
        public string Description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.cargowise.com/Schemas/Universal/2011/11")]
    public partial class DataTarget
    {

        private string typeField;

        private string keyField;

        private OrganizationAddress ownerField;

        /// <remarks/>
        public string Type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }

        /// <remarks/>
        public string Key
        {
            get
            {
                return this.keyField;
            }
            set
            {
                this.keyField = value;
            }
        }

        /// <remarks/>
        public OrganizationAddress Owner
        {
            get
            {
                return this.ownerField;
            }
            set
            {
                this.ownerField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.cargowise.com/Schemas/Universal/2011/11")]
    public partial class Staff
    {

        private string codeField;

        private string nameField;

        /// <remarks/>
        public string Code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
            }
        }

        /// <remarks/>
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.cargowise.com/Schemas/Universal/2011/11")]
    public partial class Department
    {

        private string codeField;

        private string nameField;

        /// <remarks/>
        public string Code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
            }
        }

        /// <remarks/>
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.cargowise.com/Schemas/Universal/2011/11")]
    public partial class Branch
    {

        private string codeField;

        private string nameField;

        /// <remarks/>
        public string Code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
            }
        }

        /// <remarks/>
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.cargowise.com/Schemas/Universal/2011/11")]
    public partial class DocumentaryOverride
    {

        private int dataVersionField;

        private bool dataVersionFieldSpecified;

        private string documentNameField;

        private bool isSystemDefinedField;

        private bool isSystemDefinedFieldSpecified;

        private CodeDescriptionPair purposeField;

        private int submissionVersionField;

        private bool submissionVersionFieldSpecified;

        /// <remarks/>
        public int DataVersion
        {
            get
            {
                return this.dataVersionField;
            }
            set
            {
                this.dataVersionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DataVersionSpecified
        {
            get
            {
                return this.dataVersionFieldSpecified;
            }
            set
            {
                this.dataVersionFieldSpecified = value;
            }
        }

        /// <remarks/>
        public string DocumentName
        {
            get
            {
                return this.documentNameField;
            }
            set
            {
                this.documentNameField = value;
            }
        }

        /// <remarks/>
        public bool IsSystemDefined
        {
            get
            {
                return this.isSystemDefinedField;
            }
            set
            {
                this.isSystemDefinedField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IsSystemDefinedSpecified
        {
            get
            {
                return this.isSystemDefinedFieldSpecified;
            }
            set
            {
                this.isSystemDefinedFieldSpecified = value;
            }
        }

        /// <remarks/>
        public CodeDescriptionPair Purpose
        {
            get
            {
                return this.purposeField;
            }
            set
            {
                this.purposeField = value;
            }
        }

        /// <remarks/>
        public int SubmissionVersion
        {
            get
            {
                return this.submissionVersionField;
            }
            set
            {
                this.submissionVersionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SubmissionVersionSpecified
        {
            get
            {
                return this.submissionVersionFieldSpecified;
            }
            set
            {
                this.submissionVersionFieldSpecified = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.cargowise.com/Schemas/Universal/2011/11")]
    public partial class Company
    {

        private string codeField;

        private Country countryField;

        private string nameField;

        /// <remarks/>
        public string Code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
            }
        }

        /// <remarks/>
        public Country Country
        {
            get
            {
                return this.countryField;
            }
            set
            {
                this.countryField = value;
            }
        }

        /// <remarks/>
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.cargowise.com/Schemas/Universal/2011/11")]
    public enum DataContextAction
    {

        /// <remarks/>
        Merge,

        /// <remarks/>
        LinkOnly,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.cargowise.com/Schemas/Universal/2011/11")]
    public enum DataContextTriggerType
    {

        /// <remarks/>
        Trigger,

        /// <remarks/>
        Milestone,

        /// <remarks/>
        Exception,

        /// <remarks/>
        Manual,
    }
}